.eslintrc.js, .vscode/settings.json, package.json
* VS Code settings to work with enlist plugin updates
* Update Eslint "ecmaVersion" to 2018
* Added npm script for lint
=> Update ESlint settings

src/verify.js
*  missingDependencies check fix
* Shifted commandExists command to work as Promise
=> Update: optimist verify

package.json
* Removed chalk from npm dependencies
* no longer in use since #4
=> Removed Chalk From Dependencies

package.json
* cypress version 3.1.3 -> 4.11.0
* command-exists version 1.2.8 -> 1.2.9
* eslint version 5.10.0 -> 7.5.0
* mocha version 5.2.0 -> 8.0.1
=> Update: Package.json Version

.eslintrc.json, .vscode/settings.json
* Added yoda rule
* update VS code Setting to insert spaces
=> Update ESlint config update

.github/workflows/tests.yml, package-lock.json, package.json
* Added Istanbul coverage.
* Added codecov to the project.
* Added github workflow to run tests and generate coverage report.
=> Added Code Coverage Support

.github/workflows/tests.yml, .vscode/launch.json, package-lock.json, package.json, src/docker/containers/container.js, src/docker/docker.js, src/docker/types.js, test/docker/docker.js
* Added chai to the project
* Added interface to the container class see #21 
* Added  tests for Docker.CreateContianer class
=> Container Management

.github/workflows/tests.yml
* Test coverages only on 12.X environment
* Runs tests when pushed to master
=> Update Github Action Triggers

package-lock.json, package.json, src/docker/containers/container.js, src/docker/containers/preset.js, src/docker/docker.js, src/verify.js, test/docker/docker.spec.js
* Activate jest ESlint rules
* Added rules for jsdoc
=> ESlint Config Update

.github/workflows/tests.yml, .vscode/launch.json, package.json, src/docker/containers/container.js, test/docker/containers/container.spec.js, test/docker/docker.spec.js, test/util.js
* Added Tests for docker/**container.js
* Added ability to jest
* Fixed coverage files for jest
* Added util to create and delete test containers
* Fixed Container.logs()
=> Add Tests For Docker Container

package.json
=> Removing Dockerode

package.json
* keywords for the repo
* repository data
* bugs info
* directories info
=> Updated Package.json Config

package-lock.json, test/docker/containers/container.spec.js
* update package-lock.json
* Fied Tests
=> Remove Dockerode

src/docker/containers/container.js, src/docker/docker.js, src/docker/types.js, src/docker/util.js, src/docker/volume.js, test/docker/containers/container.spec.js, test/docker/docker.spec.js, test/docker/util.spec.js, test/docker/volume.spec.js
* Added interface to create and delete volume. see #28 
* exported ReturnPromise to util file.
=> Add Volume Management

src/docker/containers/container.js, src/docker/docker.js, src/docker/network.js, src/docker/types.js, src/docker/util.js, src/docker/volume.js, test/docker/containers/container.spec.js, test/docker/docker.spec.js, test/docker/network.spec.js, test/docker/util.spec.js, test/docker/volume.spec.js
* Added interface to control docker network. see #41 
* Added method to clean docker inspect data.
=> Add Interface To Control Networks

.github/workflows/tests.yml
* change CI tests run when pushing to main.
see #36
=> Change Ci For root branch to main

package.json
=> Add Lint For Pre Push

src/wp-cli/plugin.js, src/wp-cli/types.js, test/wp-cli/plugin.spec.js
Updated to WP CLI - Plugin management. see #53 
newly API and types
* Added: activate - Activate one or more plugins.
* Added: deactivate - Deactivate one or more plugins.
* Added: delete - Deletes one or more plugins.
* Added: get - Get plugin data.
* Added: install - Installs one or more plugins.
* Added: isActive - Checks if a given plugin is active.
* Added: isInstalled - Checks if a given plugin is installed.
* Added: path - Gets the path to a plugin or to the plugin 
* Added: list - Return list of plugin installed in the wordpress site and there data.
* Added: uninstall - Uninstalls one or more plugins.
=> Feature/wp cli/plugins

package.json
Wordpress have the property nicename to it's users
=> Added Nicename To Work Skip

test/wp-cli/plugin.spec.js, test/wp-cli/theme.spec.js
update the jest hook to reset the WPcommand before each test
=> Update Jest Hooks

package-lock.json, package.json
* Removed: lint-staged
* Removed pre-commit hook
* Add: npm run all
The pre-commit made the whole programming process become slow and the lint test should be in the pre-push commit.
=> Remove Pre Commit

src/docker/docker.js
Added a method in the docker class to pull docker images.
=> Added Method To Pull Docker Images 

package-lock.json, src/README.md
Created README.md. this close #39
=> Created README.md

src/docker/docker.js
Added: filter to volume attachment to add only volumes and not bines
Added: check at env variables to check if undefined instead of falsy
this PR Fix #95
=> Fix Error when Creating wordpress:cli Container On Site Init

.husky/post-checkout
Added git hook for post checkout to automatically install dependencies if package-lock.json changes
=> Added post checkout hook

src/docker/container.js, src/docker/docker.js, src/runner.js
The Container Class now gets two arguments, options, and volumes.
the volumes property Is an array of Volume objects. this enables us to delete those volumes when we delete the container
This fixes #96
=> Deleting External Volumes Of Container

package.json
Updated and published version 0.1.1 of cypress-for-WordPress.
=> Update To Version 0.1.1

license.txt, package.json
Added GPLv2 license to the project
=> Added License To The Project

.github/workflows/tests.yml, .snyk, README.md, package-lock.json, package.json
* Added snyk to the project.
* Github actions 
* Badge to the readme
* script to test at push
close #110
=> Added Snyk To The Project

CONTRIBUTING.md
Added CONTRIBUTING.md to the project. close #107
=> Added CONTRIBUTING.md File

src/docker/presets/containers.js
=> Update WordPress Port Check

src/config.js, src/runner.js
fixes bug that emerged in #116
=> Fix local and remote plugin not installing

.snyk, package-lock.json
update snyk alert in dev dependencies
=> Security Update

.husky/post-checkout
* Removed post-checkout git hook
=> Remove Git Hook Post Checkout

README.md
Fix install command in README. 
Fixed #124
=> docs: Fix Install Command In Readme

README.md
Fix docker skip explanation in README.
=> Fix skip docker pull in readme

src/wp-cli/userMeta.js
UserMeta.update() now return promise
=> Fixed UserMeta Update

bin/preperdocs.js, docs/plugin.md, docs/theme.md, docs/types.md, docs/user.md, docs/userMeta.md, package-lock.json, package.json, src/wp-cli/userMeta.js
* Added a script to generate documentation for WP-CLI and all costume types in the project.
* Generated docs for all WP-CLI
=> docs: Added auto docs generations

README.md
=> docs: Update GitHub action badge

.eslintrc.js
Added  `wpcli` to spell check skip Words
=> docs: Updated skip words

test/docker/container.spec.js
* Fixed "should return number of lines form logs" test
=> test: Fixed log test

.snyk, package-lock.json
Applied security patches to fix CVE-2021-23343
=> build: fixed CVE 2021 23343

.eslintrc.js, .gitignore, bin/cywp.js, bin/preperdocs.js, package-lock.json, package.json
* Added node version `^12.22.0 || ^14.17.0 || >=16.0.0`
* Updated ESLint node config
=> chore: updated eslint node
